using System.Text.Json.Serialization;
using bsky.bot.Clients.Models;
using bsky.bot.Clients.Requests;
using bsky.bot.Clients.Requests.Gemini;
using bsky.bot.Clients.Responses;
using bsky.bot.Dtos;
using bsky.bot.Utils;

namespace bsky.bot.Config;

[JsonSerializable(typeof(Post))]
[JsonSerializable(typeof(Reply))]
[JsonSerializable(typeof(Author))]
[JsonSerializable(typeof(Viewer))]
[JsonSerializable(typeof(Subject))]
[JsonSerializable(typeof(string[]))]
[JsonSerializable(typeof(Record))]
[JsonSerializable(typeof(ThreadPost))]
[JsonSerializable(typeof(ReplyRequest))]
[JsonSerializable(typeof(List<object>))]
[JsonSerializable(typeof(Notification))]
[JsonSerializable(typeof(LoginRequest))]
[JsonSerializable(typeof(LoginResponse))]
[JsonSerializable(typeof(FollowRequest))]
[JsonSerializable(typeof(ThreadPostReply))]
[JsonSerializable(typeof(GetPostResponse))]
[JsonSerializable(typeof(ConversationRep))]
[JsonSerializable(typeof(ConversationReply))]
[JsonSerializable(typeof(GenerateReplyRequest))]
[JsonSerializable(typeof(GenerateReplyResponse))]
[JsonSerializable(typeof(ListNotificationsResponse))]
[JsonSerializable(typeof(Dictionary<string, object>))]
[JsonSerializable(typeof(GetPostThread))]
[JsonSerializable(typeof(PostRequest))]
[JsonSerializable(typeof(Facet))]
[JsonSerializable(typeof(Feature))]
[JsonSerializable(typeof(Feature[]))]
[JsonSerializable(typeof(Facet[]))]
[JsonSerializable(typeof(FacetIndex))]
[JsonSerializable(typeof(bool))]
[JsonSerializable(typeof(string))]
[JsonSerializable(typeof(GetHrefMetadataResponse))]
[JsonSerializable(typeof(UploadBlob))]
[JsonSerializable(typeof(RefKeyObj))]
[JsonSerializable(typeof(Image))]
[JsonSerializable(typeof(ExternalDict))]
[JsonSerializable(typeof(GeminiGeneratedResponse))]
[JsonSerializable(typeof(GeminiCandidate))]
[JsonSerializable(typeof(GeminiResponseContent))]
[JsonSerializable(typeof(GeminiRequestPart))]
[JsonSerializable(typeof(TechPostRequest))]
[JsonSerializable(typeof(GeminiInstruction))]
[JsonSerializable(typeof(GenerationConfig))]
[JsonSerializable(typeof(PostReplyRequest))]
[JsonSerializable(typeof(LikeRequest))]
[JsonSerializable(typeof(RecordRequest))]
[JsonSerializable(typeof(Subject))]
[JsonSerializable(typeof(ArticleSummaryRequest))]
[JsonSerializable(typeof(SummarizeRequest))]
[JsonSerializable(typeof(LLMRequest))]
[JsonSerializable(typeof(SearchPostsResponse))]
[JsonSerializable(typeof(RecordEmbed))]
[JsonSerializable(typeof(PostEmbedRecord))]
[JsonSerializable(typeof(AspectRatio))]
[JsonSerializable(typeof(External))]
[JsonSerializable(typeof(ExternalPost))]
[JsonSerializable(typeof(EmbedImage))]
[JsonSerializable(typeof(PostReply))]
[JsonSerializable(typeof(FeedObject))]
[JsonSerializable(typeof(GetFeedResponse))]
[JsonSerializable(typeof(SkylineObject))]
[JsonSerializable(typeof(GetSkylineResponse))]
[JsonSerializable(typeof(RequestFile))]
[JsonSerializable(typeof(UploadFileGeminiRequest))]
[JsonSerializable(typeof(GetUploadPathResponse))]
[JsonSerializable(typeof(GeminiFile))]
[JsonSerializable(typeof(GeminiUploadFileResponse))]
internal partial class BlueSkyBotJsonSerializerContext : JsonSerializerContext
{
    
}